# Generated by Django 3.1 on 2020-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200228_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcommand',
            name='command',
            field=models.CharField(choices=[('RTL', 'Return to Launch'), ('HOLD', 'Hold at Current Position'), ('GOTO', 'Goto Position'), ('RON', 'Continue'), ('DISARM', 'Dis-Arm Aircraft'), ('ALT', 'Adjust Altitude'), ('TERM', 'Terminate Flight'), ('MAN', 'Manual')], max_length=6),
        ),
    ]
