# Generated by Django 3.0.3 on 2020-02-16 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smm_login', models.CharField(max_length=50)),
                ('smm_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('client_port', models.IntegerField(default=20202, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)])),
                ('config_port', models.IntegerField(default=8090, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)])),
                ('https', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SMMConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=443, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)])),
                ('https', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='serverconfig',
            index=models.Index(fields=['name'], name='config_serv_name_9df463_idx'),
        ),
        migrations.AddIndex(
            model_name='serverconfig',
            index=models.Index(fields=['active'], name='config_serv_active_e5a03f_idx'),
        ),
        migrations.AddField(
            model_name='assetconfig',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='assetconfig',
            name='smm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.SMMConfig'),
        ),
        migrations.AddIndex(
            model_name='assetconfig',
            index=models.Index(fields=['asset'], name='config_asse_asset_i_c1e6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetconfig',
            index=models.Index(fields=['smm'], name='config_asse_smm_id_431a75_idx'),
        ),
    ]
